runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"

automatic_scaling:
  max_instances: 3
  min_instances: 1
